# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'v1.18.2-k3s1'
      - run: |
          kubectl get nodes
          kubectl version
          sleep 30
          echo "Create hello.yaml (svc and deployment)"
          kubectl create -f hello.yaml
          sleep 20
          kubectl get svc,pods -A
          # kubectl port-forward $(kubectl get pods -l "app=hello-kubernetes" -o jsonpath="{.items[0].metadata.name}") 8080 &
          # curl localhost:8080
          kubectl run -it busybox --image=busybox:1.28 --rm --restart=Never -- sh -c 'nc -zv hello-kubernetes 80'
          kubectl run -it busybox --image=busybox:1.28 --rm --restart=Never -- sh -c 'wget hello-kubernetes; cat index.html'
